
server:
  port: ${SERVER_PORT}

spring:

  application:
    name: order-test-api

  jpa:
    open-in-view: false
    hibernate:
      show_sql: ${DB_JPA_SHOW_SQL}
      ddl-auto: ${DB_DDL_AUTO}

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}

  flyway:
    enabled: ${FLYWAY_ENABLED}

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    addresses: ${RABBITMQ_ADDRESSES}
    template:
      queues:
        consumers:
          order-queue: ${RABBITMQ_ORDER_CONSUMER}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSURE:health,info,shutdown}
    enabled-by-default: ${ACTUATOR_ENABLED:true}
  endpoint:
    info:
      enabled: true
    health:
      show-details: never